### ISSUE TITLE
[device-port] [halium-9.0] [dreamlte] Samsung Galaxy S8

### ISSUE THREAD

**Issue by pklampros** [Halium/projectmanagement#262]
Tree: 

- [x] Create manifest [samsung_dreamlte.xml](https://github.com/Halium/halium-devices/pull/312/files#diff-3e591ad619748e66e78bd398710d6e54e1ecb691e239c003d6f23147ef5be471)
- [x] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

Doesn't boot yet.

Using [this unofficial LineageOS build/source/device tree](https://forum.xda-developers.com/t/rom-unofficial-dreamlte-dream2lte-sm-g950f-sm-g955f-9-lineageos-16-0.3899829/)

Remove multiple definitions of YYLTYPE yylloc (kernel/samsung/universal8895/scripts/dtc/dtc-lexer.l and kernel/samsung/universal8895/scripts/dtc/dtc-lexer.lex.c_shipped)

Remove `$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)` and add `$(call inherit-product, $(SRC_TARGET_DIR)/product/halium.mk)` in device/samsung/dreamlte/lineage_dreamlte.mk

**Comment by tmvkrpxl0** [comment]
Hello, I'm working on Galaxy S8+ with halium-9.0
I think we can work together as they are very similar

**Comment by allaeddineomc** [comment]
> Hello, I'm working on Galaxy S8+ with halium-9.0
> I think we can work together as they are very similar

where did you got ? i'm interested in working with you

**Comment by tmvkrpxl0** [comment]
> > Hello, I'm working on Galaxy S8+ with halium-9.0
> > I think we can work together as they are very similar
> 
> where did you got ? i'm interested in working with you

I have too few linux knowledge and I decided to give up. Nothing I compile actually ran on the device. Sorry to tell you this

**Comment by vanyasem** [comment]
Consider updating https://docs.halium.org/en/latest/supplementary/devices/dream2lte.html while you're on it.

(psst https://github.com/Halium/docs/blob/master/supplementary/devices/dream2lte.rst)


or maybe you should create a new file called dreamlte (regular S8) and go from there.

IIRC dream2lte and dreamlte shared a common kernel/device tree, so those devices should be (theoretically) interchangeable. I myself worked on an S8+

**Comment by Jo-Blade** [comment]
Hello @pklampros , I've managed to build halium-boot and system.img for this device with halium 10 (I'll raise an issue later) for the dreamlte (S8). I've deployed these on my device but like you, nothing appears in the dmesg nor telnet, nor ssh. I want to know if you have had some ideas to work about this problem. (And maybe if you want us to work together ?)

**Comment by Jo-Blade** [comment]
Last thing : When I was booting the phone, the screen stuck on the "samsung galaxy s8" splashcreen for a while without doing anything (no ssh, no telnet as I said). After a couple of minutes, the phone automatically restart. However, if I go into the twrp recovery, there is no file in /sys/fs/pstore, maybe the kernel started successfully and just the usb networking failed ?

**Comment by pklampros** [comment]
@Jo-Blade sorry, haven't really progressed with this and no time to work on it atm unfortunately. Will happily test builds and changes though... I did see on the telegram UBports porting channel that @abkro had some success booting into the UI with S8, maybe they can give us some tips here?

**Comment by vanyasem** [comment]
@Jo-Blade the reboot is most likely due to the fact that the kernel booted indeed, and the process of starting an LXC container started. The LXC container failed to boot and forced a reboot of the phone. You can check that by chrooting into rootfs.img and disabling the LXC image service. if it stops rebooting after these steps, then the kernel does boot successfully, and LXC is at fault 

ssh/telnet is indeed broken in the kernel itself - it's a known fact since my first initial attempt at porting the device to halium-7. to check whether it booted or not, check if there are any new files/folders generated in `/data`

**Comment by Jo-Blade** [comment]
@vanyasem Sorry to not gave any news, but thanks to @abkro on the Telegram porting room, I've successfully built a halium-9 port for the device and booted in the UI. Furthermore, the usb is working, thanks to another guy who explains me I need to add the "usb-tethering" binary in /usr/bin of the rootfs.
I am currently trying to get sound working in the device.

I would probably open a new issue with my manifest.xml and explanation of the fixes soon.

**Comment by vanyasem** [comment]
@Jo-Blade wow, that's great news! would you mind sharing some photos? 

I am really interested in looking at your trees, please commit them anywhere you like

I will close this issue once you open a new one. I appreciate the work you've done

**Comment by Jo-Blade** [comment]
@vanyasem It is done ! #292 please contact me if you have some issues
